/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecomerce;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sashank
 */
public class Cart extends javax.swing.JFrame {
String url = "jdbc:oracle:thin:@localhost:1521:xe";
        String user = "project";
        String pass = "password";
        int cid;
    /**
     * Creates new form Cart
     */
    public Cart(int c) {
        cid = c + 400;
        initComponents();
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
 
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT item_code,price,quantity from adds where cart_id = "+cid;
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
               int i = rs.getInt("item_code");
               int p = rs.getInt("price");
               int q = rs.getInt("quantity");
               String sql1 = "select name from items where item_code = "+i;
               Statement st1 = con.createStatement();
               ResultSet r = st1.executeQuery(sql1);
               r.next();
               String n = r.getString("name");
               
               cart.add(n+" "+p+" "+q);
                
            }
            
            con.close();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cart = new java.awt.List();
        remove = new javax.swing.JButton();
        total = new javax.swing.JButton();
        order = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        remove.setText("Remove From Cart");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        total.setText("Calculate Total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        order.setText("Place Order");
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remove, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(remove)
                        .addGap(31, 31, 31)
                        .addComponent(total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(order)))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
 
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT total from adds where cart_id = "+cid;
            int total = 0;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
               int i = rs.getInt("total");
               total = total + i;
                
            }
          String infoMessage = "Total = "+total;
            JOptionPane.showMessageDialog(null, infoMessage, "Discount " , JOptionPane.INFORMATION_MESSAGE);
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }        
    }//GEN-LAST:event_totalActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            String select = cart.getSelectedItem();
            String []x = select.split(" ");
            String n = x[0];
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT item_code from items where name = '"+n+"'";
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            int item = rs.getInt("item_code");
            sql = "delete from adds where cart_id = "+cid+"and item_code = "+item;
            int m = st.executeUpdate(sql);
            if ( m == 1)
            {
                 sql = "SELECT item_code,price,quantity from adds where cart_id = "+cid;
            cart.removeAll();
             st = con.createStatement();
             rs = st.executeQuery(sql);
            while(rs.next())
            {
               int i = rs.getInt("item_code");
               int p = rs.getInt("price");
               int q = rs.getInt("quantity");
               String sql1 = "select name from items where item_code = "+i;
               Statement st1 = con.createStatement();
               ResultSet r = st1.executeQuery(sql1);
               r.next();
               String name = r.getString("name");
               
               cart.add(name+" "+p+" "+q);
                
            }
            }
            con.close();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }        
    }//GEN-LAST:event_removeActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        // TODO add your handling code here:
        String card= JOptionPane.showInputDialog("Please insert credit card number ");
        long cardno = Long.parseLong(card);
        String pin= JOptionPane.showInputDialog("Please insert credit card pin "); 
        int pinnum = Integer.parseInt(pin);
         Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
 
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            int cusid = cid - 400;
            String sql = "SELECT card_no from credit_card where c_id = "+cusid;
          // System.out.println(sql);
            int flag = 0;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
               long i = rs.getInt("card_no");
            //  System.out.println(i+" "+cardno);
               if(i == cardno)
                  flag = 1;
                
            }
            if(flag == 1)
            {
                sql = "select max(order_id) from myorder";
                rs = st.executeQuery(sql);
                rs.next();
                int oid = rs.getInt("max(order_id)");
                oid = oid + 1;
                sql = "insert into myorder values("+oid+","+cid+")";
                int m = st.executeUpdate(sql);
                if(m==1)
                {
                    JFrame frame1 = new JFrame();
             JOptionPane.showMessageDialog(frame1,"Placed Order");
                }
            }
            else
            {
                CallableStatement cStmt = con.prepareCall("{call add_card(?,?,?,?)}");
            cStmt.setLong(1,cardno);
            cStmt.setInt(2,pinnum);
            cStmt.setInt(3,cusid);
         
        
               cStmt.setInt(4,cid);
            cStmt.execute();
             JFrame frame1 = new JFrame();
             JOptionPane.showMessageDialog(frame1,"Placed Order");
            }
            
            con.close();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }        
    }//GEN-LAST:event_orderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart(104).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List cart;
    private javax.swing.JButton order;
    private javax.swing.JButton remove;
    private javax.swing.JButton total;
    // End of variables declaration//GEN-END:variables
}
