/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecomerce;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Types;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sashank
 */
public class Items extends javax.swing.JFrame {
 String url = "jdbc:oracle:thin:@localhost:1521:xe";
        String user = "project";
        String pass = "password";
        int cid;
    /**
     * Creates new form Items
     */
    public Items(int c_id) {
        cid = c_id;
        initComponents();
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
 
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT distinct(type) from items";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                String type = rs.getString("type");
                list_type.add(type);
                
            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list_type = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        list_name = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        list_price = new java.awt.List();
        discount = new javax.swing.JButton();
        cart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        view_cart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_typeActionPerformed(evt);
            }
        });

        jLabel1.setText("Type");

        jLabel2.setText("Products available");

        list_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_nameActionPerformed(evt);
            }
        });

        jLabel3.setText("Vendor");

        discount.setText("View Disount");
        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });

        cart.setText("Add to cart");
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });

        jLabel4.setText("quantity");

        view_cart.setText("View Cart");
        view_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_cartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(list_type, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(list_name, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(list_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(discount)
                        .addGap(41, 41, 41)
                        .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(view_cart)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(list_type, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(list_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(list_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discount)
                    .addComponent(cart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_cart)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_typeActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());

            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT name from items where type ='"+list_type.getSelectedItem()+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            list_name.removeAll();
            while(rs.next())
            {
                String type = rs.getString("name");

                list_name.add(type);

            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }
    }//GEN-LAST:event_list_typeActionPerformed

    private void list_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_nameActionPerformed
        // TODO add your handling code here:
         Connection con=null;
         try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());

            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT item_code from items where name ='"+list_name.getSelectedItem()+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            list_price.removeAll();
            int id;
            rs.next();            
            id = rs.getInt("item_code");
            
            sql = "select id,price from produces where item_code = "+id;
            st = con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next())
            {
                int vendor = rs.getInt("id");
                int price = rs.getInt("price");
                 
                String sql1 = "select name from vendor where id = "+vendor;
                Statement st1 = con.createStatement();
                ResultSet r = st1.executeQuery(sql1);
                r.next();
                String v = r.getString("name");
                
                list_price.add(v+" "+price);
            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }
    }//GEN-LAST:event_list_nameActionPerformed

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed
        // TODO add your handling code here:
        
     
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());

            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT item_code from items where name ='"+list_name.getSelectedItem()+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            int id;
            rs.next();            
            id = rs.getInt("item_code");
            sql = "select availabity,discount from sale where item_code = "+id;
            st = con.createStatement();
            rs = st.executeQuery(sql);
          //  rs.next();
            String infoMessage = "";
            if(!rs.next())
            {
                infoMessage = "Discount not available";
            }
            else
            {
            
                String a = rs.getString("availabity");
            int dis = rs.getInt("discount");
            
            if(a.equals("yes"))
                infoMessage = "Discount is "+dis+"%";
            else
                infoMessage = "Discount not available";
            }
            JOptionPane.showMessageDialog(null, infoMessage, "Discount " , JOptionPane.INFORMATION_MESSAGE);
            con.close();
        }
        catch(Exception ex)
        {
            System.err.print(ex);
        }
    }//GEN-LAST:event_discountActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());

            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT item_code from items where name ='"+list_name.getSelectedItem()+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            int id;
            rs.next();            
            id = rs.getInt("item_code");
            String select = list_price.getSelectedItem();
            String []x = select.split(" ");
            String v = x[0];
            Float p = Float.parseFloat(x[1]);
            sql = "select availabity,discount from sale where item_code = "+id;
            st = con.createStatement();
            rs = st.executeQuery(sql);
           if(rs.next())
           {
               
           
         
           /* String a = rs.getString("availabity");
            int dis = rs.getInt("discount");
            
            if(a.equals("yes"))
                p = p - (( p * dis)/100);*/
               String sql1 = "select id from vendor where name = '"+v+"'";
               System.out.println(sql1);
                Statement st1 = con.createStatement();
               ResultSet r= st1.executeQuery(sql1);
               r.next();
               int vid = r.getInt("id");
               CallableStatement cstmt = con.prepareCall("{? = call cal(?,?)}");
cstmt.registerOutParameter(1, Types.INTEGER);
cstmt.setInt(2, id);
cstmt.setInt(3, vid);
cstmt.execute();
p = cstmt.getFloat(1);
           }
            sql = "select cart_id from cart where c_id = "+cid;
            st = con.createStatement();
            rs = st.executeQuery(sql);
            rs.next();
            int cart = rs.getInt("cart_id");
            
            int q = Integer.parseInt(quantity.getText());
            
            sql = "insert into adds values("+id+","+cart+","+q+","+p+",default)";
            st = con.createStatement();
            int m = st.executeUpdate(sql);
            if (m == 1)
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,"Added to cart");
            }
            else
            {
             JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,"Please try again");   
            }
            con.close();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cartActionPerformed

    private void view_cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_cartActionPerformed
        // TODO add your handling code here:
        Cart c = new Cart(cid);
        
        c.setVisible(true);
        c.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_view_cartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Items(100).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cart;
    private javax.swing.JButton discount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private java.awt.List list_name;
    private java.awt.List list_price;
    private java.awt.List list_type;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton view_cart;
    // End of variables declaration//GEN-END:variables
}
