/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecomerce;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sashank
 */
public class Vendoroptions extends javax.swing.JFrame {
String url = "jdbc:oracle:thin:@localhost:1521:xe";
        String user = "project";
        String pass = "password";
        
    int vid;
    /**
     * Creates new form Vendoroptions
     */
    public Vendoroptions(int id) {
        this.vid = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        i_name = new javax.swing.JTextField();
        i_price = new javax.swing.JTextField();
        i_type = new javax.swing.JTextField();
        add_new = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        list = new java.awt.List();
        load = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        prce = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        load1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        iname = new javax.swing.JTextField();
        itype = new javax.swing.JTextField();
        iprice = new javax.swing.JTextField();
        modify = new javax.swing.JButton();
        list1 = new java.awt.List();
        select = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        list2 = new java.awt.List();
        load2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        availability = new javax.swing.JTextField();
        ChngDiscount = new javax.swing.JButton();
        ChngAvai = new javax.swing.JButton();
        AddDis = new javax.swing.JButton();
        view_discount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Price");

        jLabel3.setText("Type");

        add_new.setText("Add");
        add_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_newActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(i_name)
                            .addComponent(i_price)
                            .addComponent(i_type, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(add_new)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(i_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(i_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(i_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(add_new)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add New Items", jPanel1);

        load.setText("load");
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel9.setText("Price");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(load))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel9)
                        .addGap(71, 71, 71)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add)
                            .addComponent(prce, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(load)))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(prce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(add)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Add existing item", jPanel3);

        load1.setText("Load");
        load1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Name");

        jLabel5.setText("Price");

        jLabel6.setText("Type");

        modify.setText("modify");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        select.setText("select");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(38, 38, 38)
                                .addComponent(itype, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(iprice, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iname, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(load1)
                    .addComponent(modify)
                    .addComponent(select))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(load1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(iname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(iprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(itype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(modify)
                        .addGap(42, 42, 42))))
        );

        jTabbedPane1.addTab("Change Details", jPanel4);

        load2.setText("Load");
        load2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Discount");

        jLabel8.setText("Availability");

        ChngDiscount.setText("Change Discount");
        ChngDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChngDiscountActionPerformed(evt);
            }
        });

        ChngAvai.setText("Change Availability");
        ChngAvai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChngAvaiActionPerformed(evt);
            }
        });

        AddDis.setText("Add Discount");
        AddDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDisActionPerformed(evt);
            }
        });

        view_discount.setText("view");
        view_discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_discountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ChngAvai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(discount)
                            .addComponent(availability)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(ChngDiscount))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(view_discount)
                                    .addComponent(load2))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddDis)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(load2)
                        .addGap(18, 18, 18)
                        .addComponent(view_discount)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(availability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChngDiscount)
                    .addComponent(ChngAvai)
                    .addComponent(AddDis))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Sales", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_newActionPerformed
     Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());

            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT MAX(item_code) from items";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            int id = rs.getInt("MAX(item_code)");
            id = id+1;
            String name = i_name.getText();
            String p = i_price.getText();
            int price = Integer.parseInt(p);
            String type = i_type.getText();
            CallableStatement cStmt = con.prepareCall("{call list_items(?,?,?,?,?)}");
            cStmt.setInt(1,vid);
            cStmt.setInt(2,id);
            cStmt.setString(3,name);
         
            cStmt.setString(4,type);
               cStmt.setInt(5,price);
            cStmt.execute();
            
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,"Inserted into items");

            
con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_add_newActionPerformed

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());

            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT name from items where item_code not in (select item_code from produces where id ="+vid+")";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                String name = rs.getString("name");
                list.add(name);
                
            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_loadActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());

            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT item_code from items where name ='"+list.getSelectedItem()+"'" ;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            int id = rs.getInt("item_code");
            int price = Integer.parseInt(prce.getText());
            sql = "insert into produces values("+id+","+vid+","+price+")";
            int m = st.executeUpdate(sql);

            if (m == 1){
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,"Item listed");

            }
            else{
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,"Please try again");
            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        } // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void load1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load1ActionPerformed
 Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
 
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT name from items where item_code in (select item_code from produces where id ="+vid+")";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                String name = rs.getString("name");
                list1.add(name);
                
            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }                // TODO add your handling code here:
    }//GEN-LAST:event_load1ActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
 
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT item_code from items where name ='"+list1.getSelectedItem()+"'" ;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            int id = rs.getInt("item_code");
             sql = "update items set type = '"+itype.getText()+"' where item_code =" +id;
             st = con.createStatement();
            int m = st.executeUpdate(sql);
            sql = "update produces set price ="+iprice.getText()+" where item_code ="+id+"and id = "+vid;
             st = con.createStatement();
             m = st.executeUpdate(sql);
            if (m == 1){JFrame frame1 = new JFrame();
             JOptionPane.showMessageDialog(frame1,"Updated");
               
                
            }else{
                JFrame frame1 = new JFrame();
             JOptionPane.showMessageDialog(frame1,"Please try again");
            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }                
    }//GEN-LAST:event_modifyActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());

            //Reference to connection interface
             con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT i.item_code,i.name,i.type,p.price from items i,produces p where i.name ='"+list1.getSelectedItem()+"' and i.item_code = p.item_code";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            iname.setText("");
            itype.setText("");
            iprice.setText("");
            while(rs.next())
            {
               int id = rs.getInt("item_code");
               String name = rs.getString("name");
               String type = rs.getString("type");
               int price = rs.getInt("price");
               iname.setText(name);
               itype.setText(type);
               iprice.setText(Integer.toString(price));
            }
            
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }
    }//GEN-LAST:event_selectActionPerformed

    private void load2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load2ActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
 
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT name from items where item_code in (select item_code from produces where id ="+vid+")";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                String name = rs.getString("name");
                list2.add(name);
                
            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }             
    }//GEN-LAST:event_load2ActionPerformed

    private void ChngDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChngDiscountActionPerformed
Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
 
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT item_code from items where name ='"+list2.getSelectedItem()+"'" ;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            int id = rs.getInt("item_code");
             sql = "update sale set discount ="+discount.getText()+" where item_code =" +id;
             st = con.createStatement();
            int m = st.executeUpdate(sql);
            
            if (m == 1){JFrame frame1 = new JFrame();
             JOptionPane.showMessageDialog(frame1,"Updated");
               
                
            }else{
                JFrame frame1 = new JFrame();
             JOptionPane.showMessageDialog(frame1,"Please try again");
            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }                   
    }//GEN-LAST:event_ChngDiscountActionPerformed

    private void ChngAvaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChngAvaiActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
 
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT item_code from items where name ='"+list2.getSelectedItem()+"'" ;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            int id = rs.getInt("item_code");
             sql = "update sale set availabity ='"+availability.getText()+"' where item_code =" +id;
             st = con.createStatement();
            int m = st.executeUpdate(sql);
            
            if (m == 1){JFrame frame1 = new JFrame();
             JOptionPane.showMessageDialog(frame1,"Updated");
               
                
            }else{
                JFrame frame1 = new JFrame();
             JOptionPane.showMessageDialog(frame1,"Please try again");
            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }    
    }//GEN-LAST:event_ChngAvaiActionPerformed

    private void AddDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDisActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
 
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT item_code from items where name ='"+list2.getSelectedItem()+"'" ;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            int id = rs.getInt("item_code");
             sql = "insert into sale values('"+availability.getText()+"',"+discount.getText()+","+id+")";
             st = con.createStatement();
            int m = st.executeUpdate(sql);
            
            if (m == 1){JFrame frame1 = new JFrame();
             JOptionPane.showMessageDialog(frame1,"Updated");
               
                
            }else{
                JFrame frame1 = new JFrame();
             JOptionPane.showMessageDialog(frame1,"Please try again");
            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }    
    }//GEN-LAST:event_AddDisActionPerformed

    private void view_discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_discountActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());

            //Reference to connection interface
             con = DriverManager.getConnection(url,user,pass);
             String sql = "SELECT item_code from items where name ='"+list2.getSelectedItem()+"'" ;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            int id = rs.getInt("item_code");
             sql = "SELECT discount,availabity from sale where item_code ="+id;
            st = con.createStatement();
            rs = st.executeQuery(sql);
            discount.setText("");
           availability.setText("");
            
            while(rs.next())
            {
              
               int d = rs.getInt("discount");
               String avail = rs.getString("availabity");
               
               discount.setText(Integer.toString(d));
               availability.setText(avail);
              
            }
            
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }
    }//GEN-LAST:event_view_discountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendoroptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendoroptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendoroptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendoroptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendoroptions(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDis;
    private javax.swing.JButton ChngAvai;
    private javax.swing.JButton ChngDiscount;
    private javax.swing.JButton add;
    private javax.swing.JButton add_new;
    private javax.swing.JTextField availability;
    private javax.swing.JTextField discount;
    private javax.swing.JTextField i_name;
    private javax.swing.JTextField i_price;
    private javax.swing.JTextField i_type;
    private javax.swing.JTextField iname;
    private javax.swing.JTextField iprice;
    private javax.swing.JTextField itype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.List list;
    private java.awt.List list1;
    private java.awt.List list2;
    private javax.swing.JButton load;
    private javax.swing.JButton load1;
    private javax.swing.JButton load2;
    private javax.swing.JButton modify;
    private javax.swing.JTextField prce;
    private javax.swing.JButton select;
    private javax.swing.JButton view_discount;
    // End of variables declaration//GEN-END:variables
}
